### ISSUE TITLE
🧽 Keep it DRY

### ISSUE THREAD

**Issue by boisgera** [clemence64300/TP-AP#1]
A l'heure actuelle, dans le fichier `snake.py`, le fragment de code

    snake.pop()
    a = snake[0].copy()
    a[0] += direction[0]
    a[1] += direction[1]
    snake.insert(0, a)

est répété 4 fois. Modifier le code pour faire en sorte qu'il n'apparaisse plus qu'une fois (principe [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself))

**Comment by clemence64300** [comment]
J'ai modifié avec le commit **"Black et issue"** _(1 parent [845b93a]/commit 6887e9a8b19ce4240d2684d1ca8f0b1f456837b9)_
